jwt-signature:
  signature: "![+7jgdDIxdq2tHdwrPtmuifF5760yBXDuN2f0iE/h1FmzFGg+Gm7hNTORiocctoSXipaaLzZhwcKCGGlg2+GipWA0OefDSGvPNfyOQtOMN9JnG8xAbHWDyKFIZ+K+1HeJ]"
cb-workday-sys-api:
  headers:
    password: "![NntQcX1XErDW9hIe+XS93vWZknxEmxpF5uk6sZdBHDY=]"

client_id: "![XZ4OEPiUkQzZuGpBcgmplGL9kynla5EBgeCXToCmeXc8kzrBvTNnWJ3lMsvzE23n]"
client_secret: "![Cd4PtWp5SN/pHMOJyJ4KBTcApjWjFgNYQGqCR6+PlYwSO1ZO4SixmoejBDnJUhac]"